### ISSUE TITLE
[Bug] Error Loading Playlist after login

### ISSUE THREAD

**Issue by Goldenfreddy0703** [Goldenfreddy0703/plugin.audio.ytmusic.exp#32]
Hey @fischcode i did not know where to contact you about this so i made a small but report here. Apparently when logging in for the first time, it starts loading the playlist but after loading it, it pops up an error and thats probably related to the search bug i faced as well. If you can take a look at this when your not busy that would be awesome. 

Thank you

[kodi.log](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/files/13823383/kodi.log)

Also if you wanna talk more about this and all. Please contact me and all on either discord or keybase. Here are my contacts:

## Contact

Discord: The Steampunk Owl#3126

Keybase: [Goldenfreddy0703](https://keybase.io/goldenfreddy0703)

**Comment by fischcode** [comment]
﻿Hi @Goldenfreddy0703From you logfile it looks like you have been using version beta18 instead of the most recent beta21: When I try to load the playlist causing the error with the current version, all looks OK to me. Could you please double check and let me know of any error still occurring?Thank you————————-Bernt FischerReutlingerstrasse 18CH-5000 Aarau+41 78 614 48 76Am 03.01.2024 um 22:11 schrieb Goldenfreddy0703 ***@***.***>:﻿
Hey @fischcode i did not know where to contact you about this so i made a small but report here. Apparently when logging in for the first time, it starts loading the playlist but after loading it, it pops up an error and thats probably related to the search bug i faced as well. If you can take a look at this when your not busy that would be awesome.
Thank you
kodi.log
Also if you wanna talk more about this and all. Please contact me and all on either discord or keybase. Here are my contacts:
Contact
Discord: The Steampunk Owl#3126
Keybase: Goldenfreddy0703

**Comment by Goldenfreddy0703** [comment]
Wait your kidding right, I thought I looked over the versions and that it was updating in my hooty repo. Will look into it again, sorry to bother you.
Thank you

**Comment by Goldenfreddy0703** [comment]
Hey so im going to go ahead and close this sense i forgot to but if same issues arise then will open this back up. 
Thank you

**Comment by Goldenfreddy0703** [comment]
Hey @fischcode , for i updated to the latest version and everything and search seems fixed so thank you. One small problem im still having is playlist cause for some odd reason, i get a value error, if you can look into that, that would be great thank you.

[kodi.log](https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/files/13867466/kodi.log)

**Comment by fischcode** [comment]
Value error was caused by a video with an alleged duration of 5'230:08:08 hours. As videos with a length of 1'000 h and more don't make much sense, @Goldenfreddy0703  decided to remove the video and not apply any change to the code.
