### ISSUE TITLE
1.0-beta32 release is giving "no tracks found" error all the time

### ISSUE THREAD

**Issue by jcjdammers** [Goldenfreddy0703/plugin.audio.ytmusic.exp#46]
Hi,
I tried the 1.0-beta32 that was released today.
However I get "no tracks found" error message on the screen all the time, no matter what menu item I choose.
See also my log:
https://paste.kodi.tv/ipijigumob

And screen picture:
![ytm](https://github.com/user-attachments/assets/e4de9d05-645b-4efa-a270-40a7500af5f6)

**Comment by Goldenfreddy0703** [comment]
Yeah, there is a general problem with YT Music / YouTube no longer supporting OAuth. You can find more on this on issue #45

**Comment by jcjdammers** [comment]
Thanks for the update.
I tried to manually create my headers_auth.json file, but it didn't work.
I think I will wait for the new solution then.

**Comment by fischcode** [comment]
Hi everyone. Actually the hint with the YouTube addon pointed in the right direction: I've added support for configuring API Client Id and API Client Secret necessary to keep OAuth working in the latest release. Please use the values you're already using for the youtube addon.
As always, the release might not show up in the repos right away: You may have to download the code if you are among the first to test.

**Comment by AndrewNNZ** [comment]
Ok, so I tried release 33. Google gave me a realy long api key but after entering that it then wanted the secret. I tried my google password but no go. Where do you get the secret from?

**Comment by jcjdammers** [comment]
Hi @fischcode , @Goldenfreddy0703 ,

I installed the 1.0-beta33 release.
Authentication with ClientID and Secret is working fine.
The addon is now loading the YouTube libraries and is giving an error at 90% when it is loading the Playlists.
It keeps trying and continuously gives the error.
See screenshots and attached kodi.log file.
[kodi.log](https://github.com/user-attachments/files/18061169/kodi.log)

![ytm1](https://github.com/user-attachments/assets/e91e7e51-c68b-4a4a-b289-4bdd664cfadd)

![ytm2](https://github.com/user-attachments/assets/159d7790-e793-4f8e-8e92-5c0e3533fc6a)

**Comment by fischcode** [comment]
Please download and install the code from the latest commit (not yet released) to fix this particular fault.

**Comment by jcjdammers** [comment]
@fischcode , I have tested the latest commit and it works well. Many thanks!!
Can you create a new release?

**Comment by AndrewNNZ** [comment]
Getting:
youtubekodi has not completed the Google verification process. The app is currently being tested, and can only be accessed by developer-approved testers. If you think you should have access, contact the [developer](https://accounts.google.com/)

**Comment by Goldenfreddy0703** [comment]
> Getting: youtubekodi has not completed the Google verification process. The app is currently being tested, and can only be accessed by developer-approved testers. If you think you should have access, contact the [developer](https://accounts.google.com/)

Thats wierd, did you follow the wiki and do all the steps to get the client and secret and stuff?
https://github.com/Goldenfreddy0703/plugin.audio.ytmusic.exp/wiki/Personal-API-Keys

**Comment by AndrewNNZ** [comment]
Yes I did follow instructions and got client id and secret. entered them and got further than i did last time. Do I need to recreate them?

Does youtubekodi sound right? Maybe i need to create a new project?

**Comment by AndrewNNZ** [comment]
error is 403 access denied

**Comment by Goldenfreddy0703** [comment]
Mmmm possibly, you may need to follow the instructions on the youtube addon sense it has better documentation over there.

**Comment by AndrewNNZ** [comment]
ok, will give it a go

**Comment by AndrewNNZ** [comment]
it seems to think it is me creating a new app when i try to get o auth credentials

**Comment by AndrewNNZ** [comment]
I have tried to create a new project to get oauth id. Then it wants developer email. Do i use mine. Definately getting client id and secret

**Comment by jcjdammers** [comment]
Hi @Goldenfreddy0703 ,
Would you be so kind to create a new release that contains the fix above? So I can install it from "repository.ytmusic" repo and have auto-updates again.
Many thanks for all the good work!!

**Comment by AndrewNNZ** [comment]
Created new keys from scratch. Using latest version. This time it just comes up no tracks found, whatever i do

**Comment by fischcode** [comment]
According to Google [developers.google.com/youtube/registering_an_application](https://developers.google.com/youtube/registering_an_application) and from my experience, an API key is NOT required for OAuth login.
Yet in the future it might be worth while experimenting with using a single personal API key instead of the plethora of keys contained in pytubefix's innertube.py which appear to be prone to become invalid: I will try that approach the next time when pytubefix fails again.
What I still don't know is the exact scope of the credentials required - the options here have greatly increased since 2021 when I created my first set of credentials for the youtube addon. I am currently using credentials created for the Youtube Data API v3 for TV and limited input devices with some access to my personal data - but I never did any systematic testing of this and was hoping for the crowd intelligence of the youtube addon user community to identify the exact criteria necessary to get a set of working parameters. Maybe a more restricted scope is with no access to personal data is also sufficient, cf. e.g. https://github.com/Kuschranada/plugin.video.youtube/wiki/Personal-API-Keys. But as said, I haven't done any systematic testing myself...

**Comment by AndrewNNZ** [comment]
Yeah, I am not sure what I did to make it work as I spent a lot of time faffing about. However
I regenerated the keys, typed them in, got no tracks, edited settings.xml, put the keys in again and as a guess added one for the api key, saved this and rebooted, then when I went to it is asked for me to go to google.com/device with the code so i did that and then it told me it was unsafe but i continued any way and then it worked!

Thanks for all your efforts and I am enjoying listening to my music again!
